# Antigen config
## Load Antigen
source ~/.antigen/antigen.zsh

## Core library
antigen use oh-my-zsh

## Theme
antigen theme robbyrussell/oh-my-zsh themes/agnoster

## Antigen bundles
antigen bundles <<EOBUNDLES
colored-man-pages
command-not-found
git
pip
python
tmux
ssh-agent
virtualenv
web-search
#zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-history-substring-search
zsh-users/zsh-syntax-highlighting
rupa/z
EOBUNDLES

## OS-specific bundles
if [[ $CURRENT_OS == 'OS X' ]]; then
    antigen bundle brew
    antigen bundle brew-cask
    antigen bundle gem
    antigen bundle osx
fi

## Tell antigen we're done
antigen apply

# Zsh config
setopt append_history
setopt auto_cd
setopt auto_pushd
setopt complete_in_word
setopt correct
setopt extended_glob
setopt extended_history
setopt hash_list_all
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt long_list_jobs
setopt no_beep
setopt no_glob_dots
setopt no_hup
setopt no_sh_word_split
setopt notify
setopt pushd_ignore_dups
setopt unset
setopt vi

HISTFILE=~/.histfile
HISTSIZE=1000

bindkey fd vi-cmd-mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

alias rm='rm -i'
if [ -f ~/.local/zshrc ]; then source ~/.local/zshrc; fi
